apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.name}}
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://{{env.heketi_cli_server}}:8080"
  restuser: "admin"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:3"
