apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.pv.name}}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{.nfs.mountpath}}
    server: {{.nfs.serverIP}}
