apiVersion: v1
kind: Secret
metadata:
  name: {{.name}} 
  namespace: {{.namespace}}
type: Opaque
data:
  {{secret.name.1}}: {{echo .value.1 | baser64}} 
  {{secret.name.2}}: {{echo .value.2 | baser64}} 
  {{secret.name.3}}: {{echo .value.3 | baser64}} 
