apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{.namespace}}
  name: {{.name}}
spec:
  serviceName: "{{.name}}"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: {{.name}}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{.name}}
          image: {{.image}}
          imagePullPolicy: {{.image.pull.policy}}
          env:
            - name: ENV_1 
              value: "1"
            - name: ENV_2
              value: "2"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG 
              valueFrom:
                configMapKeyRef:
                  name: {{.configmap.name}}
                  key: {{.configmap.key}} 
          ports:
            - containerPort: {{.port.1}}
            - containerPort: {{.port.2}}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: {{.claim}}
              mountPath: {{.mount.path}}
            - name: {{.config.name}} 
              mountPath: {{.mount.path}}
              readOnly: true
              #subPath: {{.config.file}}
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: {{.claim}}
          persistentVolumeClaim:
            claimName: {{.claim.name}}
        - name: {{.config.name}} 
          configMap:
            name: {{.configmap.name}}
